name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # her gün UTC gece 03:00'te günceller
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Wakatime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
